In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
with open('df.pkl', 'rb') as file:
       df= pickle.load(file)

In [3]:
df.head()

,price_per_sqft,area,bedrooms,floor_number,area_type,property_age,bathroom,property_type,locality
0,16243.0,985,2.0,middle_floor,Not Specified,not_specify,2,Apartment/Flat,Kurla
1,20588.0,850,2.0,lower_floor,Super Built-up Area,moderately_new,2,Apartment/Flat,Sadan wadi
2,40728.0,933,2.0,Not Specified,Not Specified,not_specify,2,Apartment/Flat,Chembur
3,34950.0,2000,6.0,Not Specified,Not Specified,not_specify,7,independent_house/villa,Chembur
4,27777.0,1015,2.0,Not Specified,Not Specified,not_specify,2,Apartment/Flat,Mulund

In [2]:
cor=pd.read_csv('location_with_coordinates.csv',usecols=['locality','latitude','longitude'])

In [3]:
cor=cor.dropna()

In [20]:
coordinate['locality'].unique().shape

(323,)

In [27]:
df['locality'].unique().shape

(323,)

,price_per_sqft,area,bedrooms,floor_number,area_type,property_age,bathroom,property_type,locality,latitude,longitude
0,16243.0,985,2.0,middle_floor,Not Specified,not_specify,2,Apartment/Flat,Kurla,19.065280,72.879380
1,16243.0,985,2.0,middle_floor,Not Specified,not_specify,2,Apartment/Flat,Kurla,19.065280,72.879380
2,16243.0,985,2.0,middle_floor,Not Specified,not_specify,2,Apartment/Flat,Kurla,19.065280,72.879380
3,16243.0,985,2.0,middle_floor,Not Specified,not_specify,2,Apartment/Flat,Kurla,19.065280,72.879380
4,16243.0,985,2.0,middle_floor,Not Specified,not_specify,2,Apartment/Flat,Kurla,19.065280,72.879380
...,...,...,...,...,...,...,...,...,...,...,...
191288,40000.0,500,1.0,higher_floor,Carpet Area,new_property,2,Apartment/Flat,Dadar,19.019227,72.842848
191289,40000.0,500,1.0,higher_floor,Carpet Area,new_property,2,Apartment/Flat,Dadar,19.019227,72.842848
191290,40000.0,500,1.0,higher_floor,Carpet Area,new_property,2,Apartment/Flat,Dadar,19.019227,72.842848
191291,40000.0,500,1.0,higher_floor,Carpet Area,new_property,2,Apartment/Flat,Dadar,19.019227,72.842848
191292,40000.0,500,1.0,higher_floor,Carpet Area,new_property,2,Apartment/Flat,Dadar,19.019227,72.842848